// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:df0a172c-f7a4-4c18-9657-cf8b00b99838",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_LUtNOq39L",
    "aws_user_pools_web_client_id": "4k5c7f5i9vtu4bekd298o5u4jm",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://3ao2sauspc.execute-api.us-west-2.amazonaws.com/master",
            "region": "us-west-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://5a5gaol4fjgjdb3qg7lmbmutg4.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "merchachadev7media61056-master",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
