declare module '*.svg'
declare module '*.gif'
declare module '*.png'
declare module '*.jpg'

declare module '@appbaseio/reactivesearch/lib/server'
declare module 'react-headroom'
declare module 'react-copy-to-clipboard'
declare module 'react-slick'
declare module 'uuid'
declare module 'aws-amplify'
declare module 'aws-amplify-react'
declare module 'react-lazy-load-image-component'
declare module 'query-string'
